### ISSUE TITLE
To-Do

### ISSUE THREAD

**Issue by yadkit** [promex-io/ts3-image#2]
## 30.05.2018 (concerning https://github.com/promex-io/ts3-image/commit/471360482df1f4930ad74c3ebebc72491679fa1e)
- [x] SID is not persistent. (https://github.com/promex-io/ts3-image/issues/2#issuecomment-392985925)
- [x] Set the token with our own. (https://github.com/promex-io/ts3-image/commit/f9022a4600058614adc9e3e0f2da3b565b6c486e)
- [x] Adapt it for usage in IaaS.

**Comment by yadkit** [comment]
Added the function to take the runtime argument to set the Serveradmin password (https://github.com/promex-io/ts3-image/commit/f9022a4600058614adc9e3e0f2da3b565b6c486e).

Second fixed.

**Comment by yadkit** [comment]
No adaption needed for private IaaS platform.
